AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for E-Commerce MySQL Database (RDS Free Tier)'

Parameters:
  DBName:
    Default: 'ecommerce_db'
    Description: 'The database name'
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DBUser:
    Default: 'admin'
    Description: 'The database admin account username'
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DBPassword:
    NoEcho: 'true'
    Description: 'The database admin account password (must be at least 8 characters containing letters and numbers)'
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9!@#%^&*()]*'

Resources:
  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable access to RDS MySQL'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: '0.0.0.0/0' # For demonstration/ease of use. Ideally restrict to App Runner/EC2 security group.

  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: '20'
      DBInstanceClass: 'db.t3.micro' # Free tier eligible
      Engine: 'mysql'
      EngineVersion: '8.0'
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      PubliclyAccessible: 'true' # Needed if App Runner is not in VPC, or for local testing.
      BackupRetentionPeriod: '0' # Disable backups for dev/test to save space

Outputs:
  DBEndpoint:
    Description: 'RDSEndpoint'
    Value: !GetAtt DBInstance.Endpoint.Address
  DBPort:
    Description: 'RDSPort'
    Value: !GetAtt DBInstance.Endpoint.Port
  JDBCConnectionString:
    Description: 'JDBC Connection String'
    Value: !Sub 'jdbc:mysql://${DBInstance.Endpoint.Address}:${DBInstance.Endpoint.Port}/${DBName}'
